### ISSUE TITLE
Blok experiment dashboard has stale data?

### ISSUE THREAD

**Issue by groovecoder** [mozilla/testpilot_metrics#10]
I think this is a known issue - is there a bug for it?

https://sql.telemetry.mozilla.org/dashboard/blok-executive-summary seems to be stuck with data from Oct 7? No new data since then.

**Comment by ghost** [comment]
@ilanasegall is working on a fix.

**Comment by groovecoder** [comment]
Any progress here? I'm getting some breakage reports in the GitHub repo. I'd like to check how often they're occurring via the Blok dashboard so I can tell users what priority we may be giving their issues.

**Comment by ghost** [comment]
(@ilanasegall is out until tomorrow)

**Comment by ghost** [comment]
@ilanasegall is backfilling Mau/Dau now _(was tempted to write nau)_.  Her second priority is Tracking Protection (then Mid Vid, then NM404, then everything else).

**Comment by groovecoder** [comment]
I see updated data!! Thank you!! Is the regular/cron job fixed now so it will continue to update automatically? If so I'll close this issue.

Also, can someone point me to a link or resource that explains how to read/interpret the "User Engagement by Cohort" report?

**Comment by ghost** [comment]
@groovecoder - we think things are all stable, but let's give it a day :).  The backpopulation script was successful, but I want to see the daily job work too.

As always, let us know if you have any questions/comments/requests for this data.

**Comment by groovecoder** [comment]
Hmm ... the latest data shown onBlok: Disable/Enable Pings report on the dashboard is from Oct 26 00h. Does that mean the daily job didn't run on 27th or 28th? 😢

**Comment by sunahsuh** [comment]
@groovecoder The job's still running for 10/27 -- they're scheduled to start at 12pm UTC (5am PT) and are currently taking between 3 to 4 hours to run. We won't get data from 10/28 until tomorrow's run since we're still getting pings for today.

**Comment by ghost** [comment]
@groovecoder @sunahsuh - dashboard has since been refreshed for 10/27.  Looks like we're up and running! :)

**Comment by groovecoder** [comment]
![giphy](https://cloud.githubusercontent.com/assets/71928/19826059/22f5ffd8-9d48-11e6-92d2-9953f0b868ed.gif)
